### ISSUE TITLE
Test data not displayed correctly

### ISSUE THREAD

**Issue by jmemmons** [GHPReporter/Ghpr.MSTest#17]
When executing tests with a `[DataTestMethod]` attribute, the reporter is appending the test data to the test name instead of putting it in the test data tab of the report

**Expected behavior**
The test name should have been "VerifyDemographicParsing" and the test data that was submitted should have been in the Test Data tab

**Screenshots**
![image](https://user-images.githubusercontent.com/6455186/52364638-54f72280-2a0b-11e9-9a44-d315604dc38b.png)

![image](https://user-images.githubusercontent.com/6455186/52364709-76f0a500-2a0b-11e9-82ad-98b917288810.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  71.0.3578.98

**Additional context**
I run this command from Jenkins CI to build and run tests as well as generate test reports:
`vstest.console.exe [Unit test dll path] /Settings:[your test.runsettings file path] /Logger:trx'`

**Product Versions**
 - Ghpr Console - 0.8.0.2
 - MSTest.TestAdapter - v1.1.18
 - MSTest.TestFramework V2 - v1.1.18

**Comment by elv1s42** [comment]
Hi @jmemmons, 

Thank you for this issue. 
Are you able to reproduce the error using the latest Ghpr.Core and Ghpr.Console packages?
Also can you please send the `.trx` file example or at least the corresponding `UnitTestResult` and `UnitTest` sections?
I can apply the fix to ignore the remaining part of the name.

`Test data` tab is used to only display the data which was added inside the tun method.
Please see this test example:
https://github.com/GHPReporter/Ghpr.NUnit.Examples/blob/9aaaef069f85b2d05d94e28248315f0a36e26526/Ghpr.NUnitExamples/Cat1/TestClass1.cs#L42

In the report the test data will be displayed like this:
http://ghpreporter.github.io/report/tests/index.html?testGuid=11111111-1111-1111-1111-111111111111&itemName=test_20190111_145659728.json&currentTab=test-data

![image](https://user-images.githubusercontent.com/6689884/52414402-45540880-2af5-11e9-8a2f-d169f5500e0f.png)

**Comment by elv1s42** [comment]
Closing this one as far as there were no extra comments.
