### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by rputch** [GHPReporter/Ghpr.MSTest#7]
Can we have an example? On how to generate the report using ms test please

**Comment by elv1s42** [comment]
Hi @rputch !

Ghpr.MSTest is a simple console application to produce reports from MSTest .trx test result files.
You can simply run your tests and then run command to generate the report:
![image](https://user-images.githubusercontent.com/6689884/30900670-8938923e-a36d-11e7-844a-e8d408a5bea7.png)

You can see short instructions in the README file: https://github.com/GHPReporter/Ghpr.MSTest#usage

Also you can take a look at the examples repository here: https://github.com/GHPReporter/Ghpr.MSTest.Examples

For examples repository we have post-biuld event to generate the report:
![image](https://user-images.githubusercontent.com/6689884/30900767-d41067e6-a36d-11e7-962d-6fbe3a6540f5.png)
